spring:
  datasource:
    url: jdbc:mysql://database-2.ckvoxrdychzo.ap-northeast-2.rds.amazonaws.com:3306/find_pill?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: gjspark513
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true