
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:db}:3306/find_pill?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: wip
    password: wip1999
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
